require "bvim.options"
require "bvim.keymaps"
require "bvim.plugins"
require "bvim.colorscheme"
-- require "bvim.coq"
require "bvim.cmp"
require "bvim.lsp"
require "bvim.telescope"
require "bvim.treesitter"
require "bvim.comment"
require "bvim.autopairs"
require "bvim.nvim-tree"
